# Generated by Django 4.2.4 on 2023-09-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_short',
            field=models.CharField(max_length=10),
        ),
    ]
