# Generated by Django 4.2.4 on 2023-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="role_type",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("CLIENT", "Client")],
                default="ADMIN",
                max_length=10,
            ),
        ),
    ]
