# Generated by Django 4.2.4 on 2023-09-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherapp", "0003_alter_clients_role_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="logos",
            field=models.ImageField(default="None", upload_to="client_logos/"),
        ),
    ]
